version = 1
SPDX-PackageName = "calendarsupport"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/calendarsupport"

[[annotations]]
path = [".gersemirc", "src/next/README", ".krazy", "src/calendarsupport-index.qdoc", "src/calendarsupport.qdoc", "src/calendarsupport.qdocconf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
